### ISSUE TITLE
Trade checklist polishing

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1025]
- [ ] decrease the size of the headline of the trade calculator
- [x] add warning when closing the feedback without save button
- [x] use correct pattern for selected days in the trade checklist calendar
- [ ] add "change" button instead of the edit icon
- [x] use the same font as the text, also divide it in threes 

decrease the size of the headline of the trade calculator
![Snímka obrazovky 2024-04-26 o 15 26 13](https://github.com/vexl-it/vexl/assets/25779015/afb507ed-d6f6-4308-b17a-3ed6f06ca9ec)
add warning when closing the feedback without save button 
![Snímka obrazovky 2024-04-26 o 15 27 42](https://github.com/vexl-it/vexl/assets/25779015/e0d4ff01-800f-44f0-8edb-21f188f4d53d)
use correct pattern for selected days in the trade checklist calendar
![Snímka obrazovky 2024-04-26 o 15 28 30](https://github.com/vexl-it/vexl/assets/25779015/e08e9f5c-4324-4bd0-8659-22bab62ea21f)
add "change" button instead of the edit icon
![Snímka obrazovky 2024-04-26 o 15 29 34](https://github.com/vexl-it/vexl/assets/25779015/a122d89c-425a-4708-8063-ab7577e56091)
use the same font as the text, also divide it in threes 
![Snímka obrazovky 2024-04-26 o 15 30 27](https://github.com/vexl-it/vexl/assets/25779015/2c15cfa6-57d9-444a-badd-5b2f97959d3a)

**Comment by leomira** [comment]
the change button is gone :D all of the rest of the issues are duplicates of #973 , so I am closing this
