### ISSUE TITLE
Implement metrics tracking into grafana

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#3]
Metrics to expose to Prometheus: 

Messages: 
- [x] Total number of messages
- [x] Number of unread messages(where pulled = false)

User: 
- [x] Number of users
- [x] Number of removed users

Contacts: 
- [x] Number of users
- [x] Number of contacts
- [x] Number of connections

Offers (pro buy & sell): 
- [x] All time number of offers
- [x] Number of active offers
- [x] Number of today modified offers
- [x] Number of removed offers
- [x] Počet živých nabídek (refreshed at > now()) ???? 
- [ ] Histogram flagů
- [ ] 5, 50, 95 percentil

**Comment by kaladivo** [comment]
see https://www.notion.so/satoshilabs/Dashboard-Spec-5376853c561d4986a68b431cbd3d3acf

**Comment by kaladivo** [comment]
Number of flags (histogram)
